// <auto-generated />
namespace Yogam.AMC.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class CardNum : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CardNum));
        
        string IMigrationMetadata.Id
        {
            get { return "201601131947498_CardNum"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
